DATA:
  IMG_SIZE: 448
PRETRAIN:
  PATH: checkpoint/swin_small_patch4_window7_224.pth
MODEL:
  TYPE: swin
  NAME: swin_small_patch4_window7_448
  DROP_PATH_RATE: 0.3
  NUM_CLASSES: 1000
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7